#pragma once

#define STEERING_MOD .15
#define FRICTION_MOD 1.3
#define ACCEL_MOD 7.5
#define FRAMERATE 30
#define BEAM_SPEED 30
#define BEAM_COOLDOWN 5
#define ASTEROID_SPEED 5
#define ASTEROID_SPAWNRATE 10
#define ASTEROID_HEALTH 2
#define INV_FRAMES 30
#define PARTICLE_LIVETIME 30
#define PARTICLE_SIZE 4
#define LOGICAL_WIDTH 1920.0
#define LOGICAL_HEIGHT 1080.0