#pragma once
#define STEERING_MOD .15
#define FRICTION_MOD 1.3
#define ACCEL_MOD 7.5
#define FRAMERATE 30
#define BEAMSPEED 30
#define BEAMCOOLDOWN 5
#define ASTEROIDSPEED 5
#define ASTEROIDSPAWNRATE 10
#define ASTEROIDHEALTH 3